apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcpx

resources:
  - weather-deployment.yaml
  - utilities-deployment.yaml
  - filesystem-deployment.yaml
  - services.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: mcpx
      app.kubernetes.io/component: mcp-servers
    includeSelectors: false
